[toolchain]
# Old version of Anchor used 'yarn'
# See https://www.anchor-lang.com/docs/updates/release-notes/0-31-0
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
election = "81CwxRyxTd3RWSZT6x3w5RjLTFcudVri3i9KsmWpifCk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# We need '--test-reporter=spec' to get a more readable output on GitHub CI
# this has no effect on local runs
test = "npx create-codama-clients; npx tsx --test --test-reporter=spec tests/*.ts"
